### ISSUE TITLE
Groovy 2.4.x not working

### ISSUE THREAD

**Issue by visch** [INFINITE-TECHNOLOGY/BOBBIN#18]
I imagine this is a Won't Fix but it looks like this doesn't work on groovy 2.4.x (maybe I need to upgrade?).  Writing this up just so someone else can find this when searching the repo / google. 

Error I get back is

java.lang.NoSuchMethodError: org.codehaus.groovy.runtime.memoize.EvictableCache.getAndPut(Ljava/lang/Object;Lorg/codehaus/groovy/runtime/memoize/MemoizeCache$ValueProvider;)Ljava/lang/Object;

After running

```
@Grab(group='io.infinite', module='bobbin', version='2.0.0')
import io.infinite.blackbox.BlackBox
import io.infinite.carburetor.CarburetorLevel
@BlackBox(level = CarburetorLevel.EXPRESSION)
String foobar(String foo) {
    String bar = "bar"
    String foobar = foo + bar
    return foobar
}
foobar("foo")
```

When running on Groovy 2.4.12

**Comment by apryamostanov** [comment]
Hi @visch !

I've seen such error while testing. Give me please couple of hours to suggest on this.
Thank you for reporting the issue! :)

**Comment by apryamostanov** [comment]
hi @visch!

After doing a bit of research on this issue, and consulting with Groovy Team (thanks to @daniel_sun !), the current recommendation is to upgrade the project to use Groovy 2.5.x (2.5.4).
It seems to be a general recommendation - to avoid using libraries compiled using different versions of Groovy.

Would this be suitable for you?

In the meanwhile I will do more research on the subject and try to find any other workarounds for our awareness.

Note: there seems to be another issue related to using Grape:
```
java.lang.RuntimeException: Error grabbing Grapes -- [download failed: org.junit.platform#junit-platform-engine;1.3.1!junit-platform-engine.jar]
```
If you encounter this issue, kindly use Gradle for timebeing with all the `infinite` libraries.
We are already working on this issue and hopefully will be able to fix it soon.

We highly appreciate your attention to the project. Please don't hesitate to report any other issues, or feedback.

Thank you so much!

**Comment by apryamostanov** [comment]
hi @visch!

I tried few options, like using
```
    compileOnly 'org.codehaus.groovy:groovy-all:2.5.4'
    testCompileOnly 'org.codehaus.groovy:groovy-all:2.5.4'
```
- to prevent transient Groovy 2.5.4 dependency, however it seems that there method change mismatch between the Groovy versions - thus impossible to fix. 
I kindly ask you to please upgrade to Groovy 2.5.4.

Reg. Grapes error:
```
java.lang.RuntimeException: Error grabbing Grapes -- [download failed: org.junit.platform#junit-platform-engine;1.3.1!junit-platform-engine.jar]
```
It's cause and solution are now found and the fixed version will be published tomorrow.

**Comment by visch** [comment]
Awesome thank you! We will be moving to a more updated version of groovy in the future (We're trying to do both the move to Java 11 and Groovy move at a similar time, and it's hard to know when we should actually make the move, as of today we're still on Java 8 and Groovy 2.4.x )

**Comment by apryamostanov** [comment]
@visch , tomorrow I will check on creating Groovy 2.4.x branch for Bobbin and other Infinite libraries (BlackBox, etc). I will research on existing practice how to organize the code (i.e. branch or forked repo).

But definitely in such case we are willing to support Groovy 2.4.x.
Please give me time until tomorrow EOD, I will advise.

Thank you.

**Comment by visch** [comment]
No rush at all. I wasn't expecting our use case to be supported! Thanks :D

**Comment by apryamostanov** [comment]
This was wrongly automatically closed; reopening.

**Comment by apryamostanov** [comment]
Hi @visch!

We have researched on the subject today and tried to prepare and publish a build with Groovy 2.4.x support.

However the result unfortunately was negative, mainly due to 2 below reasons:
- There are few external dependencies used in the projects that don't support Groovy 2.4.x (e.g. Groovy Enterprise Plugin). It would be complicated to ask their developers to add support for Groovy 2.4.x.
- There are several issues that were identified and fixed in Groovy platform itself at the course of BlackBox development. The fixes are available only in recent Groovy updates (2.5.4+).
Some of these issues are potential blockers for BlackBox, e.g.:
https://issues.apache.org/jira/browse/GROOVY-8881

You can check list of issues raised to Groovy team during BlackBox development here:
https://issues.apache.org/jira/browse/GROOVY-8938?jql=reporter%20in%20(anton.pryamostanov)

In light of this, it seems to be quite complicated to add the retrofit support for Groovy 2.4.x at this stage.

We highly value your interest about our projects and ask you to kindly use them with Groovy 2.5.4+ where feasible - and wait until your other codebase is migrated to Groovy 2.5.4+

Sorry for the frustration. Please don't hesitate to keep in touch with us.
Thank you.

**Comment by apryamostanov** [comment]
hi @visch !

I have **good news**! After some research and mix-and-match I figured out how to support different Groovy versions properly. **Now even Groovy 2.4.x is supported!**

The new versions have been published and documentations have been updated.

Here is the new example, please try it - it should work in your environment now:
```groovy
@Grab('io.infinite:blackbox:1.0.15')
@Grab('io.infinite:bobbin:2.0.3')

import io.infinite.blackbox.BlackBox
import io.infinite.carburetor.CarburetorLevel

@BlackBox(level = CarburetorLevel.EXPRESSION)
String foobar(String foo) {
    String bar = "bar"
    String foobar = foo + bar
    return foobar
}

foobar("foo")
```

Apologies for initial confusion! We really hope that you will like the libraries and will start using them in your projects.

From our side we guarantee timely support and bug-fixing.

Thank you so much!

**Comment by apryamostanov** [comment]
Once you kindly confirm, we will close this issue.

**Comment by visch** [comment]
I'll be able to take a look Sunday / Monday. Thanks again!

**Comment by visch** [comment]
Works for me now, I did have to clear out my groovy lib cache.

**Comment by apryamostanov** [comment]
Many thanks!

Highly appreciate your feedback, @visch !
